import category_theory_triangulated_categories_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace category_theory_triangulated_categories_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end category_theory_triangulated_categories_theorem_canonical_lane_mathlib
end HautevilleHouse
